version: '3'
services:
  mailN_database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgrespostgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
    volumes:
      - mailN_database:/var/lib/postgresql/projGo/data

  mailN_keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://mailN_database/postgres
      KC_DB_USERNAME: postgres_user
      KC_DB_PASSWORD: postgrespostgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adm1n
      KC_HEALTH_ENABLED: "false"
      KC_LOG_LEVEL: info
    command:
      [ "start-dev", "--http-port 7080", "--https-port 7443", "--import-realm" ]
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "7080:7080"
      - "7443:7443"
    depends_on:
      - mailN_database

volumes:
  mailN_database:
    driver: local

